// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v5.26.1
// source: common.proto

/* eslint-disable */

export const protobufPackage = "";

export interface IntArray {
  values: number[];
}

export const _PACKAGE_NAME = "";
