// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v5.26.1
// source: calc.proto

/* eslint-disable */

export const protobufPackage = "calculator";

export const CALCULATOR_PACKAGE_NAME = "calculator";
